### ISSUE TITLE
How to inject DataSource in the ICredentialRepository implment class with spring framework?

### ISSUE THREAD

**Issue by DISSIDIA-986** [wstrange/GoogleAuth#24]
@Repository
public class DatabaseCredentialsRepository implements ICredentialRepository {
	
	@Autowired
	DataSource dataSource;
init ICredentialRepository  by ServiceLoader,as above,the injected dataSource is null.
How to solve this ? thanks.

**Comment by DISSIDIA-986** [comment]
Should GoogleAuthenticator code be changed with setCredentialRepository() added?

**Comment by emcrisostomo** [comment]
Hi @DISSIDIA-986,

By looking at you previous two comments, I'm not sure how the two problems are related.

The first one you are reporting (`dataSource`) being `null`, has nothing to do with this library: why that field is not autowired depends solely on the configuration of your project.

As far as a `setCredentialRepository` method, it may certainly be useful. If one should perform such a refactoring, the current service lookup code should be adapted to live alongside setter injection (that is trivial). To answer your question: "Should the library be changed?" Well, I guess your opinion is it should since you need it.

**Comment by DISSIDIA-986** [comment]
thank you !

**Comment by emcrisostomo** [comment]
Released in [1.0.0][release].

[release]: https://github.com/wstrange/GoogleAuth/releases/tag/1.0.0
