### ISSUE TITLE
Same API Code is not working in Singapore

### ISSUE THREAD

**Issue by jgsudhakar735** [wstrange/GoogleAuth#32]
Hi All,
I Have taken your code as Reference and Created the sample JAVA Web Application and using the same in my Project and the Code is working like charm in my system (India). But the same code is not working in the Singapore. I am trying a lot but not getting the reason . Can anybody please help on this.
Reference from : https://github.com/wstrange/GoogleAuth
1. Is there any dependency with the Country name .
Thanks in Advance..

**Comment by emcrisostomo** [comment]
Hi @jgsudhakar735,

If you are using this code as a "reference" I'm afraid that instead of using this library as-is you have taken the code and adapted to your need. Therefore, I can't possibly know what you've done, let alone why it is not working.

The TOTP algorithm has no knowledge of a "country", it only uses the time. Chances are you have some problems with clocks in Singapore: make sure you represent the time in the same time zone.  In fact, I suggest you pick UTC and stick to it.
