### ISSUE TITLE
Please advise...

### ISSUE THREAD

**Issue by Jacky412** [wstrange/GoogleAuth#43]
Hi,
First of all thank you for creating such a great tool. I am currently in my University final year and are using your API to implement two factor authentication in my final year project.

However there is an issue; the storage of the secret key. Since the program requires the secret key in order to generate TOTP, I cannot possibly just store the hash, and if I were to encrypt the secret key that would means that I will have to hard code the decryption key. Furthermore my application is designed to work offline (i.e. cannot host an authentication server).

I remember our lecturer taught us in class that it is a bad practice to hard code secret key and should also never store key in clear. 

I will greatly appreciate your help if you could give me some advice and will be really grateful.

Best Regards,
Jacky

**Comment by wstrange** [comment]
You are correct: The seed (secret key) needs to be decrypted by both the server and the client in order to generate and verify the TOTP value.  A hash is not going to work - the server/client needs the original seed for the algorithm to work.

You need to use good practices on the server / client to protect the seed. This might include encrypting it with a symmetric key when it is stored in a database. The decryption key could be held in something like a hardware security module (HSM) to protect it.  

PKI has pretty much the same issue. If the private key is compromised you are in trouble.
